var rev1, rev2, rev3, rev4, rev5;
var net1, net2, net3, net4, net5;

// SVG, Scales and Axes Declaration
var revenue = d3.select("div.revenueVis")
			.append("svg")
			.attr("class", "revCanvas")
			.attr("height", height)
			.attr("width", width);

// Define Scales for Year, Fee, Color and Position
var revxScale = d3.scale.linear()
				.domain([1999, 2017])
				.range([40, 780]);

var revyScale = d3.scale.linear()
				.domain([-100, 600])
				.range([height - yPadding, yPadding + yMargin]);

var revColor = d3.scale.ordinal()
				.domain(["In", "Out"])
				.range(["#61B7D1", "#F04F5A"]);

var posScale = d3.scale.linear()
				.domain([0, 21])
				.range([2*yPadding + yMargin, height - yPadding]);

// Define x and y Axis
var revxAxis = d3.svg.axis()
					.scale(revxScale)
					.orient("bottom")
					.tickFormat(d3.format("d"));

var revyAxis = d3.svg.axis()
					.scale(revyScale)
					.orient("left")
					.ticks("7");

revenue.append("g")
	.attr("class", "axis")
	.attr("id", "barX")
	.attr("transform", "translate(0," + (height - yPadding) + ")")
	.call(revxAxis);

revenue.append("g")
	.attr("class", "axis")
	.attr("id", "barY")
	.attr("transform", "translate("+ xPadding + ","+ 0 +")")
	.call(revyAxis);

revenue.append("text")
	.attr("class", "axis-label")
	.attr("transform", "translate("+ yLabelX +","+ (yLabelY-20) +") rotate(-90)")
	.text("Revenue (in million £)");

revenue.append("text")
	.attr("class", "axis-label")
	.attr("transform", "translate("+ xLabelX +","+ xLabelY +")")
	.text("Year");


d3.csv("data/revenue/arsenal.csv", function(data){
	rev1 = data;
	showRev(rev1);
	posLineRev(pos1, revenue);
});

d3.csv("data/revenue/chelsea.csv", function(data){
	rev2 = data;
});

d3.csv("data/revenue/liverpool.csv", function(data){
	rev3 = data;
});

d3.csv("data/revenue/mancity.csv", function(data){
	rev4 = data;
});

d3.csv("data/revenue/manutd.csv", function(data){
	rev5 = data;
});

d3.csv("data/arsenal/ArsenalTransferNet.csv", function(data){
	net1 = data;
	showNet(net1);
});

d3.csv("data/chelsea/ChelseaTransferNet.csv", function(data){
	net2 = data;
});

d3.csv("data/liverpool/LiverpoolTransferNet.csv", function(data){
	net3 = data;
});

d3.csv("data/mancity/ManCityTransferNet.csv", function(data){
	net4 = data;
});

d3.csv("data/manutd/ManUtdTransferNet.csv", function(data){
	net5 = data;
});

/*
FUNCTION TO SHOW NET ANNUAL REVENUE GENERATED BY CLUBS
*/
function showRev(rev){
	revenue.selectAll(".rev-line").remove();
	revenue.selectAll(".rev-circle").remove();

	var line = d3.svg.line()
					.x(function(d){ return revxScale(d.Year); })
					.y(function(d){ return revyScale(d.Revenue); })

	var revChart = revenue.append("path")
					.datum(rev)
					.attr("class", "rev-line")
					.attr("d", line);

	var bgLineRev = revenue.append("path")
					.datum(rev)
					.attr("d", line)
					.attr("style", "fill: none; stroke:#fff; stroke-width: 25px; opacity: 0.0;");

	var revCircles = revenue.selectAll("circle")
					.data(rev)
					.enter()
					.append("circle")
					.attr("class", "rev-circle")
					.attr("cx", function(d){
						return revxScale(d.Year); })
					.attr("cy", function(d){ 
						if (d.Revenue > 0){
							return revyScale(d.Revenue); 
						}
					})
					.attr("r", 3)
					.attr("style", "fill: #fff; stroke:#40bb9c; stroke-width: 1.5px;");

	/*bgLineRev.on("mouseover",function(){
		var selLine = d3.select(".rev-line");
		var selCircles = d3.selectAll("circle");
		selLine.moveToFront();
		selCircles.moveToFront();
	});
	revChart.on("mouseover",function(){
		var selLine = d3.select(this);
		var selCircles = d3.selectAll(".rev-circle");
		selLine.moveToFront();
		selCircles.moveToFront();
	});
	revCircles.on("mouseover",function(d){
		var selCircles = d3.selectAll(".rev-circle");
		var selLine = d3.select(".rev-line");
		selLine.moveToFront();
		selCircles.moveToFront();
		showPos(d.Year, d.Pos);
	});
	bgLineRev.on("mouseout",function(){
		var selLine = d3.select(".rev-line");
		var selCircles = d3.selectAll("circle");
		selLine.moveToBack();
		selCircles.moveToBack();
	});
	revChart.on("mouseout",function(){
		var selLine = d3.select(this);
		var selCircles = d3.selectAll(".rev-circle");
		selLine.moveToBack();
		selCircles.moveToBack();
	});
	revCircles.on("mouseout",function(d){
		var selCircles = d3.selectAll(".rev-circle");
		var selLine = d3.select(".rev-line");
		selLine.moveToBack();
		selCircles.moveToBack();
		revenue.selectAll(".rev-label").remove();
	});*/
}

/*
FUNCTION TO SHOW NET ANNUAL EXPENDITURE OF CLUBS
*/
function showNet(net){
	revenue.selectAll(".net-line").remove();
	revenue.selectAll(".net-circle").remove();

	var line = d3.svg.line()
					.x(function(d){ return revxScale(d.Year); })
					.y(function(d){ return revyScale(d.Net/1000000); })

	var revNetChart = revenue.append("path")
					.datum(net)
					.attr("class", "net-line")
					.attr("d", line)
					.attr("style", "fill: none; stroke:#ea382f; stroke-width: 1.5px;");;

	var bgLineNet = revenue.append("path")
					.datum(net)
					.attr("d", line)
					.attr("style", "fill: none; stroke:#fff; stroke-width: 25px; opacity: 0.0;");

	var netCircles = revenue.selectAll(".net-circle")
					.data(net)
					.enter()
					.append("circle")
					.attr("class", "net-circle")
					.attr("cx", function(d){ return revxScale(d.Year); })
					.attr("cy", function(d){ return revyScale(d.Net/1000000); })
					.attr("r", 3)
					.attr("style", "fill: #fff; stroke:#ea382f; stroke-width: 1.5px;");
}

/*
FUNCTION TO SHOW ANNUAL LEAGUE TABLE POSITION OF CLUBS
*/
function posLineRev(pos){
	revenue.selectAll(".rev-pos-line").remove();
	revenue.selectAll(".rev-pos-circle").remove();

	var line = d3.svg.line()
					.x(function(d){ return revxScale(d.Year); })
					.y(function(d){ return posScale(d.Pos); })

	var revPosChart = revenue.append("path")
					.datum(pos)
					.attr("class", "rev-pos-line")
					.attr("d", line)
					.attr("opacity", 0.5);

	var bgLinePos = revenue.append("path")
					.datum(pos)
					.attr("d", line)
					.attr("style", "fill: none; stroke:#fff; stroke-width: 25px; opacity: 0.0;");

	var revPosCircles = revenue.selectAll(".rev-pos-circle")
					.data(pos)
					.enter()
					.append("circle")
					.attr("class", "rev-pos-circle")
					.attr("cx", function(d){
						return revxScale(d.Year); 
					})
					.attr("cy", function(d){ return posScale(d.Pos); })
					.attr("r", 3)
					.attr("style", "fill: #fff; stroke:#709ded; stroke-width: 1.5px;")
					.attr("opacity", 0.5);

	revPosCircles.on("mouseover",function(d){
		showPosRev(d.Year, d.Pos);
	});
	revPosCircles.on("mouseout",function(d){
		revenue.selectAll(".pos-label").remove();
	});
}

/*
FUNCTION TO SHOW THE POSITION OF CLUBS AS POPUP ON HOVER
*/
function showPosRev(year, pos){
	revenue.append('rect')
		.attr("class", "pos-label pos-container")
		.attr("transform", "translate("+ (revxScale(year)-36) +","+ (posScale(pos)-64) +")")
		.attr("opacity", 0.8);

	revenue.append("text")
		.attr("class", "pos-label")
		.attr("dy", "-48")
		.attr("transform", "translate("+ (revxScale(year)-18) +","+ (posScale(pos)) +")")
		.text("Year: "+ year);

	revenue.append("text")
		.attr("class", "pos-label")
		.attr("dy", "-36")
		.attr("transform", "translate("+ (revxScale(year)-18) +","+ (posScale(pos)) +")")
		.text("Position: "+ pos);
}